# Generated by Django 5.2.11 on 2026-02-06 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('boookzdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('book_reader_initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_initiator', related_query_name='transaction_initiator', to='authentication.bookreader')),
                ('book_reader_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_receiver', related_query_name='transaction_receiver', to='authentication.bookreader')),
                ('initiator_book', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiator_book', related_query_name='initiator_book', to='boookzdata.book')),
                ('receiver_book', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_book', related_query_name='receiver_book', to='boookzdata.book')),
                ('transaction_status', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_status', related_query_name='transaction_status', to='transactions.transactionstatus')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('rating', models.IntegerField(default=0)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('book_reader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.bookreader')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
        ),
    ]
